# https://taskfile.dev
version: "3"

vars:
  # https://taskfile.dev/reference/templating/
  DOCKER_COMPOSE: "docker compose"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  compose:
    cmds:
      - "{{.DOCKER_COMPOSE}} {{.TASK_ARGS}} {{.CLI_ARGS}}"

  composer:
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm phpfpm composer

  test:
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm phpfpm vendor/bin/phpunit tests/

  coding-standards:apply:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:javascript:apply
      - task: coding-standards:markdown:apply
      - task: coding-standards:php:apply
      - task: coding-standards:styles:apply
      - task: coding-standards:twig:apply
      - task: coding-standards:yaml:apply
    silent: true

  coding-standards:check:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:javascript:check
      - task: coding-standards:markdown:check
      - task: coding-standards:php:check
      - task: coding-standards:styles:check
      - task: coding-standards:twig:check
      - task: coding-standards:yaml:check
    silent: true

  coding-standards:javascript:apply:
    desc: "Apply coding standards for javascript"
    # cmds:
    #   # Cf. .github/workflows/javascript.yaml
    #   - docker compose run --rm prettier 'web/themes/custom/**/js/**/*.js' --write

  coding-standards:javascript:check:
    desc: "Apply coding standards for javascript"
    # cmds:
    #   - task: coding-standards:javascript:apply
    #   # Cf. .github/workflows/javascript.yaml
    #   - docker compose run --rm prettier 'web/themes/custom/**/js/**/*.js' --check

  coding-standards:markdown:apply:
    desc: "Apply coding standards for Markdown"
    cmds:
      # Cf. .github/workflows/markdown.yaml
      - docker compose run --rm markdownlint markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: "Apply and check coding standards for Markdown"
    cmds:
      - task: coding-standards:markdown:apply
      # Cf. .github/workflows/markdown.yaml
      - docker compose run --rm markdownlint markdownlint '**/*.md'

  coding-standards:php:apply:
    desc: "Apply coding standards for PHP"
    cmds:
      # Cf. .github/workflows/php.yaml
      - docker compose run --rm phpfpm vendor/bin/php-cs-fixer fix
    silent: true

  coding-standards:php:check:
    desc: "Apply and check coding standards for PHP"
    cmds:
      - task: coding-standards:php:apply
      # Cf. .github/workflows/php.yaml
      - docker compose run --rm phpfpm vendor/bin/php-cs-fixer fix --dry-run --diff
    silent: true

  coding-standards:styles:apply:
    desc: "Apply coding standards for styles"
    # cmds:
    #   # Cf. .github/workflows/styles.yaml
    #   - docker compose run --rm prettier 'web/themes/custom/**/css/**/*.{css,scss}' --write

  coding-standards:styles:check:
    desc: "Apply coding standards for styles"
    # cmds:
    #   - task: coding-standards:styles:apply
    #   # Cf. .github/workflows/styles.yaml
    #   - docker compose run --rm prettier 'web/themes/custom/**/css/**/*.{css,scss}' --check

  coding-standards:twig:apply:
    desc: "Apply coding standards for Twig"
    cmds:
      - docker compose run --rm phpfpm vendor/bin/twig-cs-fixer fix
    silent: true

  coding-standards:twig:check:
    desc: "Apply and check coding standards for Twig"
    cmds:
      - task: coding-standards:twig:apply
      - docker compose run --rm phpfpm vendor/bin/twig-cs-fixer lint
    silent: true

  coding-standards:yaml:apply:
    desc: "Apply coding standards for YAML"
    cmds:
      # Cf. .github/workflows/yaml.yaml
      - docker compose run --rm prettier '**/*.{yml,yaml}' --write

  coding-standards:yaml:check:
    desc: "Apply coding standards for YAML"
    cmds:
      - task: coding-standards:yaml:apply
      # Cf. .github/workflows/yaml.yaml
      - docker compose run --rm prettier '**/*.{yml,yaml}' --check
