<?php

namespace Drupal\itk_translation_extractor\Translation\Dumper;

use Drupal\Component\Gettext\PoHeader;
use Drupal\Component\Gettext\PoItem;
use Drupal\Component\Gettext\PoStreamWriter;
use Symfony\Component\Translation\Dumper\PoFileDumper as BasePoFileDumper;
use Symfony\Component\Translation\Exception\InvalidArgumentException;
use Symfony\Component\Translation\MessageCatalogue;

class PoFileDumper extends BasePoFileDumper
{
    public function dump(MessageCatalogue $messages, array $options = []): void
    {
        if (!\array_key_exists('path', $options)) {
            throw new InvalidArgumentException('The file dumper needs a path option.');
        }
        if (!\array_key_exists('output_name', $options)) {
            throw new InvalidArgumentException('The file dumper needs an output path option.');
        }

        $output = $this->formatCatalogue($messages, '', $options);
        $outputPath = $options['path'].'/'.$options['output_name'];
        file_put_contents($outputPath, $output);
    }

    public function formatCatalogue(
        MessageCatalogue $messages,
        string $domain,
        array $options = [],
    ): string {
        $header = new PoHeader();
        $writer = new PoStreamWriter();
        $writer->setHeader($header);
        foreach ($messages->getDomains() as $domain) {
            foreach ($messages->all($domain) as $source => $translation) {
                $metadata = $messages->getMetadata($domain, $source);
                $item = new PoItem();
                $item->setSource($source);
                $item->setTranslation($translation);
                $writer->writeItem($item);
            }
        }

        return parent::formatCatalogue($messages, $domain,
            $options); // TODO: Change the autogenerated stub
    }
}
